user_fav_starter_input= input("Hello and welcome to the Mew Mew Cafe. What is your favourite starter item on our menu that you would like?")
user_fav_main_input= input("Please enter your favourite main course:")
user_fav_dessert_input= input("And what dessert would you like to finish your meal with?")
user_fav_drink_input= input("And finally what drink would you like to have with your meal?")
print("So your favourite meal is ", user_fav_starter_input + "followed by ",  user_fav_main_input + " with a glass of ", user_fav_drink_input + " and finished with ", user_fav_dessert_input )